"""Nominal setup-only FC/sensor platform; dimensions are not strength ratings."""

PITCH_LIMIT_DEG = 20.0
PIVOT_MODULE_MM = (0.0, 0.0, 27.5)
PIVOT_UPPER_MM = (0.0, 0.0, 8.0)
LOCK_OFFSET_XZ_MM = (9.0, 0.0)
LUG_WIDTH_MM = 8.0
FACE_FIT_RESERVE_MM = 0.2
CHEEK_THICKNESS_MM = 3.0
CHEEK_INNER_Y_MM = (LUG_WIDTH_MM + FACE_FIT_RESERVE_MM) / 2
CHEEK_OUTER_Y_MM = CHEEK_INNER_Y_MM + CHEEK_THICKNESS_MM
BORE_DIAMETER_MM = 3.4
BOSS_RADIUS_MM = 5.0
NUT_POCKET_AF_MM = 5.9
NUT_POCKET_DEPTH_MM = 1.5
NUT_BEARING_Y_MM = CHEEK_OUTER_Y_MM - NUT_POCKET_DEPTH_MM
SCREW_LENGTH_MM = 16.0
SCREW_SKU = "M3X16_BUTTON_HEAD"
NUT_SKU = "M3_HEX_NUT"
UPPER_SKU = "InstrumentCarrier"
LOWER_SKU = "InstrumentMountBase"
